### ISSUE TITLE
Possible numeric instability?

### ISSUE THREAD

**Issue by andersgs** [gbradburd/SpaceMix#11]
Hi Gideon.

In a dataset I am currently analysing some of my short runs, and my long run seem to have some numeric stability issues:

```
748200  ----  1.907098e+13 
748300  ----  1.907098e+13 
748400  ----  1.907098e+13 
748500  ----  1.907098e+13 
Error in solve.default(par.cov) : 
  system is computationally singular: reciprocal condition number = 1.41589e-16
```

I had this problem with the both the `target` and `source-target` models, I have not tried the other models.  I am working from a smallish number of SNPs (420) and eight populations. But, they were all found to be outliers --- I was hoping to compare the neutral and outlier geogenetic maps. So, I wonder if that is what is causing the issue.

Congratulations and good luck with your new position (saw it on Twitter).

Cheers.

Anders.

**Comment by gbradburd** [comment]
Hi Anders,

Sorry for slow reply (am in the midst of a move)!  Yes I've encountered this issue before.  It seems to happen when the geogenetic distances between samples are small (and the sample-specific nugget terms are small as well).  When the MCMC enters this area of parameter-space, the parametric covariance matrix becomes almost degenerate  (@petrelharp feel free to step in here), and the determinant (in the denominator of the Wishart likelihood function) gets very, very small, so the likelihood gets very, very large, in a numerically unstable way.

This chain of events can occur in a few ways:

1) Two or more of your samples are very genetically similar, so that they should occupy the same geogenetic space with minimal nuggets (the sample-specific variance parameters).  I'd recommend a quick check (PCA, pairwise Fst, pairwise pi), to make sure that none of your samples are identical, or nearly so.  To see if this is the problem, you can also plot the posterior distribution of geogenetic locations (or pairwise geogenetic distances between samples), and see if some of them are tending toward co-location around the time the chain goes off the tracks.  If this seems to be the problem, you can drop the very similar samples, or combine them into one sample by summing their allele counts and sample sizes.

2) The chain enters this parameter space stochastically.  This doesn't seem to be the case for your data, as you say you observed this problem with multiple models.  However, I'd recommend running multiple analyses (making sure, if they're on a cluster, that they are initiated with different random number seeds), to see if it happens every time.

It can also happen early in the analysis if the chain is randomly initiated at a point in parameter space at which two or more samples are essentially in the same place (again, with small nuggets), or if you've specified starting geogenetic locations for your samples that are too close together.  This doesn't seem to have been your issue, as the problem appears to have arisen after about 7e5 MCMC iterations, but it's worth looking at what the initial parameters are, to see if the wonkiness arises there.

I doubt the issue has anything to do with whether the loci are outliers or not, unless a subset of samples are more similar genetically at outlier loci.  Hope that's helpful!
