### ISSUE TITLE
Error in make.spacemix.map.list

### ISSUE THREAD

**Issue by mlaylwar** [gbradburd/SpaceMix#14]
Hi,

I am running spacemix on a large dataset of ~3,600,000 SNPs. The spacemix analysis runs fine and generates the long run output file. However, when I try to run the make.spacemix.map.list I receive the following error.

Error in rgb(x[1L, ], x[2L, ], x[3L, ], x[4L, ]) : 
  alpha level NA, not in [0,1]
Calls: make.spacemix.map.list -> fade.admixture.source.points -> adjustcolor -> rgb

I have run the script on a subset of 500 SNPs, and both the spacemix analysis and reading in the Robj file for plotting run without errors. 

Do you know what could be causing the above error in the larger dataset?

Please see attached for the commands used.

Many thanks,

Megan
[spacemixPlot.txt](https://github.com/gbradburd/SpaceMix/files/4585037/spacemixPlot.txt)
[spacemixAnalysis.txt](https://github.com/gbradburd/SpaceMix/files/4585038/spacemixAnalysis.txt)

**Comment by gbradburd** [comment]
Hi Megan,

In the part of the code where you're getting the error, SpaceMix is trying to fade your vector of specified colors by an amount inversely proportional to the admixture proportion for each sample.  It looks like you're getting that error because somehow the `make.spacemix.map.list` function thinks the mean admixture proportion for one or more of your samples is `NA`.  To help diagnose the issue, can you load the long run output .Robj and confirm that `rowMeans(admix.proportions)` has non-`NA` values?

stay safe,
-Gideon

**Comment by mlaylwar** [comment]
Hi Gideon,

I checked and there aren't any NAs in the long run output, it gives all decimal values.

Thanks,

Megan

**Comment by gbradburd** [comment]
Hmm ok can you email me the .Robj file you're using to try to make the spacemix.map.list?

**Comment by gbradburd** [comment]
Hi Megan,

I found the issue - you have 46 samples, but you've specified a vector of colors that is of length 48, so when the function gets to the 47ths specified color, it tries to fade it using an admixture proportion that isn't there.  If you just drop 2 of your colors, you should be hot to trot.  Please let me know if this resolves your issue so I can close it out.

stay safe,
-Gideon

**Comment by mlaylwar** [comment]
It does, thank you!
